### ISSUE TITLE
Google Docs page margins not respected when extension is enabled

### ISSUE THREAD

**Issue by SuperMega-Drive** [threethan/Better-Darker-Docs-WebExtension#1]
Hey there,

Great work on this extension! Noticed a bug when using Google Docs, when the extension is on it won't respect page margins I set and words will run off the side of the page. Have disabled the extension and confirmed that regular Google Docs will respect page margins. Hope this helps!

**Comment by threethan** [comment]
Thought I'd worked around that, but seems like it still inconsistently pops up. This is an issue with kerning of subpixel smoothing on fonts, which is a bit less deterministic, and Google docs doesn't always play well with. 
In the next version I'll add an options menu that lets this feature be disabled, as I don't know how I would actually fix the issue.

**Comment by threethan** [comment]
ClearType can now be disabled as of version 1.1.0
